#!/bin/bash

set -x
set -e

composer=composer

if [ -z "$1" ] ; then
  echo -n "project name? "
  read name
else
  name=$1
fi

mkdir $name
cd $name

touch composer.json

php <<EOT
<?php
\$js=file_get_contents('composer.json');
\$dt=json_decode(\$js,true);
\$dt['extra']['asset-installer-paths']['npm-asset-library']='public/vendor';
\$dt['extra']['asset-installer-paths']['bower-asset-library']='public/vendor';
file_put_contents('composer.json',json_encode(\$dt));
EOT

curl -sS https://getcomposer.org/installer | php -- --filename=$composer


./$composer require "fxp/composer-asset-plugin:~1.0"
./$composer require "bower-asset/bootstrap:dev-master"

# (vendor)name+description are required
#./$composer validate

git init

echo "*~" >.gitignore
echo "vendor/" >>.gitignore
echo "public/vendor/" >>.gitignore
echo "composer.lock" >> .gitignore 
echo "composer.phar" >> .gitignore 

git add composer.json
git add .gitignore

